### ISSUE TITLE
Migration Management

### ISSUE THREAD

**Issue by fishtreesugar** [CNMDR3G/hathverse#2]
现在没有Schema, migration管理, 可以考虑下[dbmigrations](https://hackage.haskell.org/package/dbmigrations), [sqitch](http://sqitch.org/) 这些方案?

**Comment by scturtle** [comment]
看到还有个 [postgresql-simple-migration](https://hackage.haskell.org/package/postgresql-simple-migration)，这些方案相比较怎么样呢？另外 [persistent](https://hackage.haskell.org/package/persistent)、[persistent-postgresql](https://hackage.haskell.org/package/persistent-postgresql) 怎么样？

**Comment by fishtreesugar** [comment]
粗略看了一下 postgresql-simple-migration, 好像还可以但是跑起来有点繁琐,能直接在命令行跑, 数据库配置跟放migration的目录能约定放哪里就好了,  persistent那个migration不太行, 我看个像样点用Yesod的[项目](https://github.com/thoughtbot/carnival/tree/master/migrations)都是自己管理migration的

**Comment by scturtle** [comment]
Switched to persistent & esqueleto in 1d42b957d5833721d7a2457c375b86eb0b61b0fa.
