### ISSUE TITLE
please add readme

### ISSUE THREAD

**Issue by JulianZhang** [CNMDR3G/hathverse#4]
请增加readme，简单的说明一下项目情况。

**Comment by fishtreesugar** [comment]
@JulianZhang 目前只是个prototype, 很多东西也没定下来, 代码也不多, 有问题可以到gitter上问 :D

**Comment by JulianZhang** [comment]
其实我的疑问首先是这个项目是做什么的？是之前讨论的oj吗？

**Comment by scturtle** [comment]
嗯 OJ 那个。
